name: Packer CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
      - 'feat/fix'

  pull_request:
    branches:
      - 'main'
      - 'feat/fix'

  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: 'Deploy job to main/production'
        required: true
        default: 'no'

jobs:
  packer-test:
    runs-on: ubuntu-latest

    outputs:
      ami_id: ${{ steps.build-and-extract-ami-id.outputs.ami_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: '1.9.3'

      - name: Initialize Packer
        run: packer init .

      - name: Validate Packer template
        run: packer validate template.pkr.hcl

      - name: Build AMI and Extract AMI ID
        id: build-and-extract-ami-id
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set -x
          echo "Test JOB" > test.txt
            
  deploy-to-production:
    # if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/heads/feature/') }}
    # if: startsWith(github.ref, 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    if: github.ref == 'refs/heads/main'
    needs: packer-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    environment: prod
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Manual Approval
        id: approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: olawaleoyg
          secret: ${{ secrets.GITHUB_TOKEN }}
          minimum-approvals: 1
          issue-title: "Manual approval required for afxtern Shali-Packer pipeline"
          issue-body: |
            Workflow is pending manual review.
            URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Required approvers: [olawaleoyg]
            Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

      - name: Install or Update AWS CLI
        run: |
          if command -v aws &> /dev/null; then
            echo "AWS CLI is installed. updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "AWS CLI not found. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy AMI to production environment
        run: |
          AMI_ID=${{ needs.packer-test.outputs.ami_id }}
          echo "Deploying AMI to production environment with ID $AMI_ID"
          
      - name: Notify team of build success
        if: success()
        run: echo "Build and deployment to production environment successful for main branch"

      - name: Notify team of build failure
        if: failure()
        run: echo "Build and deployment to production environment failed for main branch"
