name: Packer CI/CD Pipeline

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  packer-test:
    runs-on: xterns

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
         version: '1.9.3'
          
      - name: Initialize Packer
        run: packer init .
        
      - name: Validate Packer template
        run: packer validate template.pkr.hcl
      
      - name: Build AMI with Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set -x
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            packer build -var "ami_tag=production" template.pkr.hcl | tee build.log
          else
            packer build -var "ami_tag=testing" template.pkr.hcl | tee build.log
          fi
          ls -l build.log

      - name: Check for build log
        run: |
          if [ ! -f build.log ]; then
            echo "Build log not found!"
            exit 1
          fi

      - name: Extract AMI id from packer
        id: extract-ami-id
        run: |
          AMI_ID=$(aws ec2 describe-images --filters "Name=name,Values=name" --query 'Images[0].ImageId' --output text)
          echo "Extracted AMI ID: $AMI_ID"
          [ -z "$AMI_ID" ] && { echo "AMI ID not found!"; exit 1; }
          echo "::set-output name=ami_id::$AMI_ID"
          

