name: Packer CI/CD Pipeline

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  packer-test:
    runs-on: xterns

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
         version: '1.9.3'
         
      - name: Set up AWS CLI
        uses: aws-actions/setup-sam@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Initialize Packer
        run: packer init .
        
      - name: Validate Packer template
        run: packer validate template.pkr.hcl
      
      - name: Build AMI with Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: packer build template.pkr.hcl
          

