name: Packer CI/CD Pipeline

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  packer-test:
    runs-on: xterns

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate AWS Credentials
        run: |
          aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
